name: Docker

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: docker

      - name: Build and push the image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: docker
          push: true
          tags: ghcr.io/gear-dapps/gear-env:latest,ghcr.io/gear-dapps/gear-env:1.0
